INSERT INTO USERS (ID,NAME,USERNAME,AGE,GENDER)
values(1,'Bonny Sinha','bosinha',36,'MALE');
INSERT INTO USERS(ID,NAME,USERNAME,AGE,GENDER)
values(2,'Amardeep Sinha','amsinha',6,'MALE');
INSERT INTO USERS(ID,NAME,USERNAME,AGE,GENDER)
values(3,'Puspan Sinha','pusinha',37,'FEMALE');

